### ISSUE TITLE
Missing requirement: setuptools

### ISSUE THREAD

**Issue by hansenp** [monarch-initiative/pyphetools#97]
If run the following command in the created virtual environment of `pyphetools`:

`import pyphetools`

then get an error message that `pkg_resources` is not found.

I can fix the error by installing setuptools into the environment.

`pip install setuptools`

**Comment by pnrobinson** [comment]
This package should not be needed for users who install with
```
pip install pyphetools
```
See here
Ensure pip, setuptools, and wheel are up to date
While pip alone is sufficient to install from pre-built binary archives, up to date copies of the setuptools and wheel projects are useful to ensure you can also install from source archives:
https://packaging.python.org/en/latest/tutorials/installing-packages/

-- let's try to reproduce the error!

**Comment by ielis** [comment]
When I do the following:
```shell
python3 -m venv bla
source bla/bin/activate
python3 -m pip list
```

I see
```
Package    Version
---------- -------
pip        22.0.2
setuptools 59.6.0
```

which most likely means I am getting `setuptool` in any virtual environment I create. I think the same happens in the [CI](https://github.com/monarch-initiative/pyphetools/blob/main/.github/workflows/python_ci.yml) environment, which is why the CI passes.

@hansenp what do you see when you create a fresh environment? Do you have `setuptools` there? If not, that would explain the issues you described.

**Comment by pnrobinson** [comment]
I think this package should be installed system wide and not by this package!
